# Generated by Django 3.2.4 on 2023-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswalkExternalelement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crosswalk_externalelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrosswalkExternalschema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=4, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crosswalk_externalschema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasatElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('synonym', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('term', models.CharField(max_length=255)),
                ('deprecated', models.IntegerField()),
                ('deprecatedon', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metasat_element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasatElementFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'metasat_element_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasatElementSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'metasat_element_segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasatFamilyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'metasat_elementfamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasatSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'metasat_segment',
                'managed': False,
            },
        ),
    ]
